export const POSTS = [
  {
    id: 1,
    name: "Great Stack",
    handle: "@greatstack",
    verified: true,
    time: "33 min ago",
    avatar: "GS",
    avatarBg: "linear-gradient(135deg,#6366f1,#8b5cf6)",
    text: "Stay ahead of the curve with fresh content on #code, #design, #startups, and everything in between. The future belongs to those who keep learning 🚀",
    likes: 248,
    comments: 42,
    image:
      "https://images.unsplash.com/photo-1593784991095-a205069470b6?w=700&q=80",
    commentList: [
      {
        id: 1,
        name: "Alison Mars",
        avatar: "AM",
        bg: "linear-gradient(135deg,#f472b6,#fb923c)",
        text: "This is so insightful, thanks!",
        time: "20 min ago",
      },
      {
        id: 2,
        name: "John Warren",
        avatar: "JW",
        bg: "linear-gradient(135deg,#6366f1,#8b5cf6)",
        text: "Totally agree 🙌",
        time: "15 min ago",
      },
    ],
  },
  {
    id: 2,
    name: "Alison Mars",
    handle: "@alisonmars",
    verified: false,
    time: "1 hr ago",
    avatar: "AM",
    avatarBg: "linear-gradient(135deg,#f472b6,#fb923c)",
    text: "Just finished redesigning our onboarding flow — drop-off rate went from 42% to 11% 🚀 #ux #design #product",
    likes: 512,
    comments: 87,
    image: null,
    commentList: [
      {
        id: 1,
        name: "Great Stack",
        avatar: "GS",
        bg: "linear-gradient(135deg,#6366f1,#8b5cf6)",
        text: "Incredible! What tool did you use?",
        time: "45 min ago",
      },
    ],
  },
  {
    id: 3,
    name: "Richard John",
    handle: "@richardj",
    verified: true,
    time: "2 hr ago",
    avatar: "RJ",
    avatarBg: "linear-gradient(135deg,#34d399,#3b82f6)",
    text: "This view from the morning hike was absolutely worth it 🏔️ #travel #nature #hiking",
    likes: 1024,
    comments: 133,
    image:
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=700&q=80",
    commentList: [
      {
        id: 1,
        name: "Sarah Kim",
        avatar: "SK",
        bg: "linear-gradient(135deg,#fbbf24,#ef4444)",
        text: "Where is this?! Stunning 😍",
        time: "1 hr ago",
      },
      {
        id: 2,
        name: "Alison Mars",
        avatar: "AM",
        bg: "linear-gradient(135deg,#f472b6,#fb923c)",
        text: "Goals 🏔️",
        time: "1 hr ago",
      },
    ],
  },
];

export const MESSAGES = [
  {
    id: 1,
    name: "Alison Mars",
    avatar: "AM",
    bg: "linear-gradient(135deg,#f472b6,#fb923c)",
    msg: "How are you?",
    time: "6 days ago",
    unread: 2,
  },
  {
    id: 2,
    name: "Richard John",
    avatar: "RJ",
    bg: "linear-gradient(135deg,#34d399,#3b82f6)",
    msg: "hi",
    time: "6 days ago",
    unread: 0,
  },
  {
    id: 3,
    name: "John Warren",
    avatar: "JW",
    bg: "linear-gradient(135deg,#6366f1,#8b5cf6)",
    msg: "This is a Bluetooth speaker",
    time: "14 days ago",
    unread: 0,
  },
];

export const CONNECTIONS = [
  {
    id: 1,
    name: "Emma Wilson",
    handle: "@emmawilson",
    avatar: "EW",
    bg: "linear-gradient(135deg,#a78bfa,#60a5fa)",
    mutual: 12,
    field: "Product Designer",
  },
  {
    id: 2,
    name: "James Park",
    handle: "@jamespark",
    avatar: "JP",
    bg: "linear-gradient(135deg,#f472b6,#fb923c)",
    mutual: 8,
    field: "Frontend Engineer",
  },
  {
    id: 3,
    name: "Nina Torres",
    handle: "@ninatorres",
    avatar: "NT",
    bg: "linear-gradient(135deg,#34d399,#3b82f6)",
    mutual: 5,
    field: "Startup Founder",
  },
  {
    id: 4,
    name: "Leo Zhang",
    handle: "@leozhang",
    avatar: "LZ",
    bg: "linear-gradient(135deg,#fbbf24,#f97316)",
    mutual: 3,
    field: "Data Scientist",
  },
  {
    id: 5,
    name: "Priya Nair",
    handle: "@priyanair",
    avatar: "PN",
    bg: "linear-gradient(135deg,#6366f1,#8b5cf6)",
    mutual: 9,
    field: "UX Researcher",
  },
];

export const DISCOVER_TOPICS = [
  {
    tag: "#design",
    posts: "12.4k posts",
    color: "bg-violet-100 text-violet-700",
  },
  { tag: "#startups", posts: "8.9k posts", color: "bg-blue-100 text-blue-700" },
  {
    tag: "#code",
    posts: "21.3k posts",
    color: "bg-emerald-100 text-emerald-700",
  },
  {
    tag: "#travel",
    posts: "34.1k posts",
    color: "bg-amber-100 text-amber-700",
  },
  { tag: "#ux", posts: "6.7k posts", color: "bg-pink-100 text-pink-700" },
  { tag: "#ai", posts: "15.2k posts", color: "bg-indigo-100 text-indigo-700" },
];
